### ISSUE TITLE
pretty nooby question.

### ISSUE THREAD

**Issue by moeiscool** [ShopifyExtras/PHP-Shopify-API-Wrapper#15]
I followed the installation guide except i downloaded it and used "composer install" but i get 
Parse error: syntax error, unexpected '$client' (T_VARIABLE) in C:\Users\Matrix\Cloud\OneDrive\WebD\ss\shopify\index.php on line 5

sometimes I can fix this missing var issue by putting "global $var" but in this case it isn't working. I feel pretty nooby considering all it is, is including autoload.php :/ I have done this kind of thing before! I swear! :P

**Comment by elyobo** [comment]
This project doesn't include an index.php, so the problem is somewhere in your code.  In the example documentation it shows initialising the client by doing
