### ISSUE TITLE
Instantiating the client

### ISSUE THREAD

**Issue by sebmaynard** [ShopifyExtras/PHP-Shopify-API-Wrapper#17]
Hi

Using your Shopify client; seems like it has a pretty friendly API!

To get it working with a private app, I had to deviate a bit from the instructions

    <?php
    require 'vendor/autoload.php';
    // Shopify::settings gave errors about unknown class Shopify
    $client = new Shopify\Client();
    $url = "thename.myshopify.com";
    $key = "the-password-field-in-the-private-app-auth-section";
    // found by looking at the source a bit :)
    $client->settings(Array("shopUrl" => $url, "X-Shopify-Access-Token" => $key));
    // try it
    print_r($client->getProducts());

Seems to work now :)

Thanks!!

**Comment by aMollusk** [comment]
You're the best. Thank you. Huge help.

**Comment by lukehatfield** [comment]
Instantiation was key for me as well. Would like to know how I could use the code as in the instructions: `$client = Shopify::settings(array(...`. Seemed like composer was working otherwise. Thanks for the note and thanks for the wrapper!

**Comment by elyobo** [comment]
Have to admit that I noticed this when I used this library a while back, but forgot to mention anything.  Digging up my old code I have the following to create the client.  Takes an alternate approach to the authentication, including it in the URL instead, and optionally configures a logger if that's of use to anyone.

```php
use GuzzleHttp\Subscriber\Log\LogSubscriber;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Monolog\Formatter\LineFormatter;
use GuzzleHttp\Subscriber\Log\Formatter;

function get_shopify_client($key, $pass, $domain, $log) {
    $client = new Shopify\Client(array(
        'shopUrl' => sprintf(
            '%s:%s@%s', $key, $pass, $domain
        ),
        'X-Shopify-Access-Token' => null,
    ));

    if ($log) {
        $logger  = new Logger('name');
        $handler = new StreamHandler($log, Logger::DEBUG);
        $handler->setFormatter(new LineFormatter(null, null, true));
        $logger->pushHandler($handler);
        $client->getEmitter()->attach(
            new LogSubscriber($logger, Formatter::SHORT . "\n" . Formatter::DEBUG)
        );
    }

    return $client;
}
```

**Comment by ubergeekzone** [comment]
Works like a champ thanks @sebmaynard

**Comment by bxmas13** [comment]
Perfect thanks @sebmaynard

**Comment by daniel-farina** [comment]
Thanks, the instructions on the read me are all wrong/outdated.^^;
