### ISSUE TITLE
What exactly does it do?

### ISSUE THREAD

**Issue by remotetech** [ShopifyExtras/PHP-Shopify-API-Wrapper#47]
Hi, can this code be run locally on Windows 10 like a dashboard allowing me to find out the status of my Customers Installed Shopify App Status?  Status such as Active, accepted, pending, declined or expired? 

Please advise....Thank you!

**Comment by elyobo** [comment]
No, it's not an application, it's a library for developers to use when writing an application.

**Comment by remotetech** [comment]
Thank you for the clarification!
