### ISSUE TITLE
Get Order

### ISSUE THREAD

**Issue by amol-kolhe** [ShopifyExtras/PHP-Shopify-API-Wrapper#49]
Error Occur : Error executing command: cURL error 6: Could not resolve host: https

**Comment by cargix1** [comment]
Please ensure you that you are providing a valid myshopify.com url when creating your client. 

`$client = new \Shopify\Client([
   "shopUrl" => '**shopifyextras.myshopify.com**',
   "X-Shopify-Access-Token" => $accessToken
]);`
