### ISSUE TITLE
Support for new Price Rules endpoint?

### ISSUE THREAD

**Issue by bxmas13** [ShopifyExtras/PHP-Shopify-API-Wrapper#59]
Any updates for the upcoming Price Rules endpoint?

[Ruby Example](https://github.com/Shopify/shopify_api/pull/335/commits/e22366f687100b4309ad4d5ec2e42cfd63ccb938)

**Comment by chiwek** [comment]
just posted a pull request on this..

**Comment by cargix1** [comment]
Changed merged, thanks @chiwek
